version: "3.3"
services:
  api:
    build:
      context: api
      target: prod
      args:
        dataset: ml-latest
  frontend:
    depends_on: [api]
    build:
      context: frontend
      target: prod
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://api
    ports:
      - "3000:3000"
