version: "3.3"
services:
  api:
    build:
      context: api
      target: dev
      args:
        dataset: ml-latest-small
    volumes:
      - ./api/app:/app
    ports:
      - "5000:80"
  frontend:
    depends_on: [api]
    build:
      context: frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://api
    ports:
      - "3000:3000"
